# Generated by Django 5.1.1 on 2024-10-22 19:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'db_table': 'production_schedule',
            },
        ),
        migrations.CreateModel(
            name='ScheduleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('phase', models.IntegerField()),
                ('priority_order', models.IntegerField()),
                ('quantity', models.FloatField()),
                ('completion_time', models.FloatField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.productionschedule')),
            ],
            options={
                'db_table': 'schedule_details',
            },
        ),
    ]
