# Generated by Django 5.1.1 on 2024-10-22 21:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploaded_file', models.FileField(upload_to='schedules/')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='processed_schedules/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.RemoveField(
            model_name='scheduledetail',
            name='schedule',
        ),
        migrations.CreateModel(
            name='EquipmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=100)),
                ('priority_order', models.TextField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_schedules', to='schedule.schedule')),
            ],
            options={
                'db_table': 'equipment_schedule',
            },
        ),
        migrations.DeleteModel(
            name='ProductionSchedule',
        ),
        migrations.DeleteModel(
            name='ScheduleDetail',
        ),
    ]
