# Generated by Django 5.1.1 on 2024-10-22 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_remove_scheduledetail_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='processed_file',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='title',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ScheduledProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('equipment', models.CharField(max_length=255)),
                ('priority_score', models.FloatField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_products', to='schedule.schedule')),
            ],
            options={
                'db_table': 'scheduled_product',
            },
        ),
        migrations.DeleteModel(
            name='EquipmentSchedule',
        ),
    ]
