# Generated by Django 5.1.1 on 2024-10-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_schedule_processed_file_remove_schedule_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('equipment_name', models.CharField(max_length=255)),
                ('phase', models.CharField(max_length=50)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='uploaded_file',
            new_name='schedule_file',
        ),
        migrations.AddField(
            model_name='schedule',
            name='processed_file',
            field=models.FileField(blank=True, null=True, upload_to='processed_schedules/'),
        ),
        migrations.AlterModelTable(
            name='schedule',
            table=None,
        ),
        migrations.DeleteModel(
            name='ScheduledProduct',
        ),
    ]
