# Generated by Django 5.1.1 on 2024-10-14 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
            ],
            options={
                'db_table': 'composition',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(default='', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='composition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.product'),
        ),
        migrations.AddField(
            model_name='composition',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.ingredient'),
        ),
        migrations.AlterUniqueTogether(
            name='composition',
            unique_together={('ingredient', 'product')},
        ),
    ]
