# Generated by Django 5.1.1 on 2024-10-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_composition_ingredient_delete_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(default='', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='composition',
            unique_together={('product', 'ingredient')},
        ),
    ]
