# Generated by Django 5.1.1 on 2024-10-22 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_equipment_alter_ingredient_ingredient_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('equipment_name', models.CharField(max_length=255)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.equipment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.product')),
            ],
            options={
                'db_table': 'equipment_product_relation',
            },
        ),
    ]
